random_seeds: [42]
confidence: 0.95

data_source: openml # from "openml", "synthetic"
openml_params:
    suite_id: 353

results_csv_name: results.csv

predictor_model: RandomForestRegressor
predictor_params:
    n_estimators: 500
    oob_score: True

data_augmentation:
    sigma_knn_dist: False
    sigma_knn_std: False
    sigma_knn_res: False
    sigma_var: False

loss_functions: [bin_crossfit]
lambda_cov : 500
ncp_knn_k: 25

sr_params:
    npopulations: 40
    population_size: 50
    niterations: 10
    binary_operators: ["+", "-", "*", "/"]
    unary_operators: ["logm(x) = log(abs(x) + 1f-8)", "exp"]
    nested_constraints: {
        # "sin": {"cos": 0, "sin": 0}, 
        # "cos": {"cos": 0, "sin": 0},
        "logm": {"logm": 1},
        "exp": {"exp": 0}
    }
    temp_equation_file: False

extra_regressors:
    random_forest: 
        activate: True
        n_estimators: 500
    extra_regressor2:
        param: []